name: nothing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Bloc for state management
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  # Service locator
  get_it: ^7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Remote API
  http: ^1.0.0
  # Router API
  go_router: ^7.1.1
  #https://pub.dev/packages/intl
  intl: ^0.18.1
  #Annotations for freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # Value equality
  equatable: ^2.0.5
  connectivity_plus: ^4.0.1

  # Local cache
  shared_preferences: ^2.1.1

  dartz: ^0.10.1
  sqflite: ^2.2.8+4

  test: ^1.23.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  mockito: ^5.4.1

flutter:
  uses-material-design: true
